import Head from 'next/head';
import { HeaderProps } from './Header.interfaces';

export function Header(props: HeaderProps) {
    return (
        <Head>
            <title>{props.title ? props.title : 'Debt Advisors - America'}</title>
            <meta charSet="utf-8"/>
            <meta name="description" content={props.description ? props.description : 'Generated by create next app'}/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="/favicon.ico"/>
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
            <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet"/> 
        </Head>
    );
};
